import { writeFileSync, existsSync, mkdirSync } from 'fs'
import { join, resolve } from 'path'
import { input, checkbox, password, confirm } from '@inquirer/prompts'
import chalk from 'chalk'
import ora from 'ora'

// ─── Types ────────────────────────────────────────────────────────────────────

type Connector = 'slack' | 'github' | 'drive'

interface InitConfig {
  installDir: string
  connectors: Connector[]
  apiPort: string
  uiPort: string
  // Slack
  slackToken: string
  slackChannels: string
  slackHistoryDays: string
  // GitHub
  githubToken: string
  githubRepos: string
  // Drive
  googleKeyPath: string
  googleFolderIds: string
}

// ─── Docker Compose template ──────────────────────────────────────────────────

const DOCKER_COMPOSE = `services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: capytrace
      POSTGRES_PASSWORD: capytrace
      POSTGRES_DB: capytrace
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U capytrace']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      retries: 5
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - '6333:6333'
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - '11434:11434'
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  qdrant_data:
  ollama_data:
`

// ─── .env generator ───────────────────────────────────────────────────────────

function generateEnv(config: InitConfig): string {
  const lines: string[] = [
    '# CapyTrace Configuration — generated by capytrace init',
    '# Re-run "capytrace init" to update',
    '',
    '# ── Infrastructure ─────────────────────────────────────────',
    'REDIS_HOST=localhost',
    'REDIS_PORT=6379',
    'QDRANT_URL=http://localhost:6333',
    'OLLAMA_URL=http://localhost:11434',
    '',
    '# ── API Server ──────────────────────────────────────────────',
    `API_PORT=${config.apiPort}`,
    `UI_PORT=${config.uiPort}`,
    'WORKER_CONCURRENCY=5',
  ]

  if (config.connectors.includes('slack')) {
    lines.push(
      '',
      '# ── Slack ───────────────────────────────────────────────────',
      `SLACK_BOT_TOKEN=${config.slackToken}`,
      `SLACK_CHANNELS=${config.slackChannels}`,
      `SLACK_SYNC_HISTORY_DAYS=${config.slackHistoryDays}`,
    )
  }

  if (config.connectors.includes('github')) {
    lines.push(
      '',
      '# ── GitHub ──────────────────────────────────────────────────',
      `GITHUB_TOKEN=${config.githubToken}`,
      `GITHUB_REPOS=${config.githubRepos}`,
      'GITHUB_INDEX_README=true',
      'GITHUB_INDEX_ISSUES=true',
      'GITHUB_INDEX_PRS=true',
      'GITHUB_INDEX_CODE=false',
    )
  }

  if (config.connectors.includes('drive')) {
    lines.push(
      '',
      '# ── Google Drive ─────────────────────────────────────────────',
      `GOOGLE_SERVICE_ACCOUNT_KEY=${config.googleKeyPath}`,
      `GOOGLE_DRIVE_FOLDER_IDS=${config.googleFolderIds}`,
      'GOOGLE_INDEX_DOCS=true',
      'GOOGLE_INDEX_SHEETS=true',
      'GOOGLE_INDEX_SLIDES=true',
    )
  }

  return lines.join('\n') + '\n'
}

// ─── Wizard ───────────────────────────────────────────────────────────────────

export async function runInit(): Promise<void> {
  console.log()
  console.log(chalk.bold('  🦫 CapyTrace Setup Wizard'))
  console.log(chalk.gray('  Corporate knowledge search engine — self-hosted'))
  console.log()

  // ── Installation directory ─────────────────────────────────────────────────
  const rawDir = await input({
    message: 'Installation directory:',
    default: process.cwd(),
  })
  const installDir = resolve(rawDir)

  // ── Idempotency: check for existing .env ──────────────────────────────────
  const envPath = join(installDir, '.env')
  if (existsSync(envPath)) {
    const overwrite = await confirm({
      message: chalk.yellow('.env already exists. Overwrite it?'),
      default: false,
    })
    if (!overwrite) {
      console.log(chalk.gray('\n  Existing .env kept unchanged.'))
      printNextSteps(installDir, '3000', '5173')
      return
    }
  }

  // ── Connector selection ────────────────────────────────────────────────────
  console.log()
  const selectedRaw = await checkbox<string>({
    message: 'Which connectors do you want to activate?',
    choices: [
      { name: 'Slack', value: 'slack' },
      { name: 'GitHub', value: 'github' },
      { name: 'Google Drive', value: 'drive' },
    ],
  })
  const connectors = selectedRaw as Connector[]

  if (connectors.length === 0) {
    console.log(chalk.yellow('\n  No connectors selected — you can add them later by editing .env'))
  }

  // Defaults for credentials (filled in per connector below)
  const config: InitConfig = {
    installDir,
    connectors,
    apiPort: '3000',
    uiPort: '5173',
    slackToken: '',
    slackChannels: '',
    slackHistoryDays: '30',
    githubToken: '',
    githubRepos: '',
    googleKeyPath: './credentials/google-service-account.json',
    googleFolderIds: '',
  }

  // ── Slack credentials ──────────────────────────────────────────────────────
  if (connectors.includes('slack')) {
    console.log(chalk.cyan('\n  Slack  →  https://api.slack.com/apps'))
    config.slackToken = await password({ message: '  Bot Token (xoxb-...):' })
    config.slackChannels = await input({
      message: '  Channel IDs (comma-separated):',
      default: '',
    })
    config.slackHistoryDays = await input({
      message: '  Sync history days:',
      default: '30',
    })
  }

  // ── GitHub credentials ─────────────────────────────────────────────────────
  if (connectors.includes('github')) {
    console.log(chalk.cyan('\n  GitHub  →  https://github.com/settings/tokens'))
    config.githubToken = await password({ message: '  Personal Access Token (ghp_...):' })
    config.githubRepos = await input({
      message: '  Repositories (owner/repo, comma-separated):',
      default: '',
    })
  }

  // ── Google Drive credentials ───────────────────────────────────────────────
  if (connectors.includes('drive')) {
    console.log(chalk.cyan('\n  Google Drive  →  https://console.cloud.google.com'))
    config.googleKeyPath = await input({
      message: '  Service account key path:',
      default: './credentials/google-service-account.json',
    })
    config.googleFolderIds = await input({
      message: '  Drive Folder IDs (comma-separated):',
      default: '',
    })
  }

  // ── Ports ──────────────────────────────────────────────────────────────────
  console.log()
  config.apiPort = await input({ message: 'API port:', default: '3000' })
  config.uiPort = await input({ message: 'UI port:', default: '5173' })

  // ── Write files ─────────────────────────────────────────────────────────────
  console.log()
  const spinner = ora('Writing configuration...').start()

  try {
    if (!existsSync(installDir)) {
      mkdirSync(installDir, { recursive: true })
    }

    writeFileSync(envPath, generateEnv(config), 'utf-8')

    const composePath = join(installDir, 'docker-compose.yml')
    if (!existsSync(composePath)) {
      writeFileSync(composePath, DOCKER_COMPOSE, 'utf-8')
      spinner.succeed('Created .env and docker-compose.yml')
    } else {
      spinner.succeed('Updated .env (existing docker-compose.yml kept)')
    }
  } catch (err) {
    spinner.fail(chalk.red('Failed to write files'))
    throw err
  }

  printNextSteps(installDir, config.apiPort, config.uiPort)
}

function printNextSteps(dir: string, apiPort: string, uiPort: string): void {
  console.log()
  console.log(chalk.bold('  Next steps:'))
  console.log()
  console.log(`  ${chalk.gray('1.')} Start infrastructure:`)
  console.log(`     ${chalk.cyan('docker compose up -d')}`)
  console.log()
  console.log(`  ${chalk.gray('2.')} Pull the embedding model ${chalk.gray('(first run only)')}:`)
  console.log(`     ${chalk.cyan('ollama pull nomic-embed-text')}`)
  console.log()
  console.log(`  ${chalk.gray('3.')} Install dependencies & start the app:`)
  console.log(`     ${chalk.cyan('pnpm install && pnpm dev:all')}`)
  console.log()
  console.log(`  ${chalk.gray('4.')} Open the UI:`)
  console.log(`     ${chalk.cyan(`http://localhost:${uiPort}`)}`)
  console.log()
  console.log(chalk.gray(`  Config written to: ${dir}/.env`))
  console.log(chalk.green('\n  ✓ Ready to launch!'))
  console.log()
}
